import {FuelType, Vehicle, VehicleType} from '@carRental/models';

export class VehicleMockData {
    public static defaultVehicles: Vehicle[] = [
        {
            db: 1,
            brandName: 'Honda',
            modelName: 'Civic',
            modelYear: 2024,
            transmissionType: 'auto',
            type: VehicleType.car,
            color: 'gray',
            fuelType: FuelType.petrol,
            people: 5,
            imgPath: 'assets/images/rentimg3.png',
        },
        {
            db: 1,
            brandName: 'Subaru',
            modelName: 'Outback',
            modelYear: 2023,
            transmissionType: 'auto',
            type: VehicleType.car,
            color: 'blue',
            fuelType: FuelType.petrol,
            people: 5,
            imgPath: 'assets/images/rentimg.png',
        },
        {
            db: 1,
            brandName: 'Volkswagen',
            modelName: 'Golf',
            modelYear: 2024,
            transmissionType: 'auto',
            type: VehicleType.car,
            color: 'white',
            fuelType: FuelType.petrol,
            people: 5,
            imgPath: 'assets/images/rentimg2.png',
        },
        {
            db: 1,
            brandName: 'Jeep',
            modelName: 'Wrangler',
            modelYear: 2024,
            transmissionType: 'manual',
            type: VehicleType.car,
            color: 'green',
            fuelType: FuelType.petrol,
            people: 4,
            imgPath: 'assets/images/rentimg.png',
        },
        {
            db: 1,
            brandName: 'Chevrolet',
            modelName: 'Corvette',
            modelYear: 2023,
            transmissionType: 'auto',
            type: VehicleType.car,
            color: 'red',
            fuelType: FuelType.petrol,
            people: 2,
            imgPath: 'assets/images/rentimg3.png',
        },
        {
            db: 1,
            brandName: 'Tesla',
            modelName: 'Model S',
            modelYear: 2024,
            transmissionType: 'auto',
            type: VehicleType.car,
            color: 'red',
            fuelType: FuelType.electricity,
            people: 4,
            imgPath: 'assets/images/rentimg.png',
        },
        {
            db: 1,
            brandName: 'Mercedes-Benz',
            modelName: 'E-Class',
            modelYear: 2023,
            transmissionType: 'auto',
            type: VehicleType.car,
            color: 'silver',
            fuelType: FuelType.petrol,
            people: 5,
            imgPath: 'assets/images/rentimg2.png',
        },
        {
            db: 1,
            brandName: 'Toyota',
            modelName: 'Prius',
            modelYear: 2024,
            transmissionType: 'auto',
            type: VehicleType.car,
            color: 'green',
            fuelType: FuelType.hybrid,
            people: 5,
            imgPath: 'assets/images/rentimg3.png',
        },
        {
            db: 1,
            brandName: 'Audi',
            modelName: 'Q7',
            modelYear: 2024,
            transmissionType: 'auto',
            type: VehicleType.car,
            color: 'black',
            fuelType: FuelType.diesel,
            people: 7,
            imgPath: 'assets/images/rentimg.png',
        },
        {
            db: 1,
            brandName: 'Lamborghini',
            modelName: 'Aventador',
            modelYear: 2024,
            transmissionType: 'auto',
            type: VehicleType.car,
            color: 'yellow',
            fuelType: FuelType.petrol,
            people: 2,
            imgPath: 'assets/images/rentimg2.png',
        },
    ] as Vehicle[];
}
