name: CI/CD
run-name: ${{ github.actor }} pushing new image to DockerHub 🚀

# Triggers the workflow on every push to master branch
on:
  push:
    branches:
      - master

jobs:
  BuildAndPushToRegistry:
    runs-on: ubuntu-latest
    environment: buildEnv
    
    steps:
      # Step 1: Checkout the repository
      - uses: actions/checkout@v4

      # Step 2: Set up Node.js to run your project builds and tests
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '16.14'
          
      # Step 3: Install project dependencies
      - run: npm install

      # Step 4: Run the tests for the API service
      - run: npx nx run api:test

      # Step 5: Build the API and car rental services
      - run: npx nx build api
      - run: npx nx build carRental

      # Step 6: Log in to DockerHub using secrets for authentication
      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 7: Extract metadata (tags, labels) for Docker image
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: mbturan/car-rental

      # Step 8: Build and push the Docker image to DockerHub
      - name: Build and push Docker image
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}